dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: wORz8nUO09Z+9Ii5ZhzbKQT/YDfkx2WCNZPsR0qNwfk1I1E36CsRyC1gJW5E+PAKP5D0k/xceh0FtImK3+GcDbeW8YyPbKIaSykxszAW8eRGoo4r43SYfCpVYDmF4JDuuLBchPGFy1wwKasuWomXCvrBUOh6FftsHwop6sXSOhFfnh9DG2GEFgOLBDRH3YHaf8K3w/h+9wZCkBI+b8bEQTaVUw27Qc9NUnRPTEBZ2t1I/YUqkKb/PaWY7AGeNaCJJbXdrgl7dneyvwLHklQijcRTLW35i8e2xQM4qZ2bgW7UXotUXMXPD65W/FRChuS5AR580ZM4IJdQv8SrAK7l6Gz8bjFzTWelmvSJFJPKoXFkXIgu3+MtJdDcdMUyS0Hbl/LXUcDligwtK9nMiU4Pg+6AtuVJzHQTSCcSvKezM2ORLog2MjDMXd91Ae1rmkpt3uHZBmMS5wY0I+QFKOK8/uI2vtOUfHRlmaKZblHXiQHeON/rQvngjN+omn9+OiiHAfRHGXpcR0ESIWHi4sTWRC/bn2bPs1aCrYq+nd9tKekkg0nUfMhLejjafgh96iFbvKgePPwyo8qfuEcMkSk2ZzxpgWGPCEj2le6ChqJbdd9dQQXqpKhe5yMshetUdicqU+kKKQ6b7pQUzOgjqYZpEdZDrLNJb+/imiwVaNriK8g=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_tsl2561.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-tsl2561 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
